HShop/HShop/Controllers/ClientsController.cs
using AutoMapper;
using HShop.Data;
using HShop.Helpers;
using HShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Principal;

namespace HShop.Controllers
{
    public class ClientsController : Controller
    {
        private const string ToastMessage = "ToastMessage";
        private const string ToastType = "ToastType";
        private const string ToastTypeSuccess = "success";
        private const string ToastTypeError = "error";
        private readonly Hshop2023Context db;
        private readonly IMapper _mapper;

        public ClientsController(Hshop2023Context db, IMapper mapper)
        {
            this.db = db;
            this._mapper = mapper;
        }

        [HttpGet]
        [Route("/admin/clients/create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser(ClientVM client, IFormFile? image)
        {
            var clientExist = await db.KhachHangs.FirstOrDefaultAsync(k => k.MaKh == client.MaKH);
            if (clientExist != null)
            {
                TempData[ToastMessage] = "Người dùng đã tồn tại (username đã tồn tại)";
                TempData[ToastType] = ToastTypeError;
                return RedirectToAction("Create");
            }

            if (!ModelState.IsValid)
            {
                TempData[ToastMessage] = "Dữ liệu không hợp lệ";
                TempData[ToastType] = ToastTypeError;
                return RedirectToAction("Create");
            }
            try
            {
                var clientInfo = _mapper.Map<KhachHang>(client);
                clientInfo.RandomKey = MyUtil.GenerateRandomKey();
                clientInfo.MatKhau = client.MatKhau.ToMd5Hash(clientInfo.RandomKey);
                clientInfo.HieuLuc = true; // sẽ xử lý khi dùng mail để active

                if (image != null)
                {
                    clientInfo.Hinh = MyUtil.UpLoadHinh(image, "KhachHang");
                }

                await db.KhachHangs.AddAsync(clientInfo);
                await db.SaveChangesAsync();
                TempData[ToastMessage] = "Tạo người dùng thành công";
                TempData[ToastType] = ToastTypeSuccess;
                return Redirect("/admin/clients");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                TempData[ToastMessage] = "Lỗi hệ thống khi thêm khách hàng";
                TempData[ToastType] = ToastTypeError;
                return RedirectToAction("Create");
            }

        }

        [HttpGet]
        [Route("/admin/client/update/{id}")]
        public async Task<IActionResult> Update(string? id)
        {
            var Client = await db.KhachHangs.FirstOrDefaultAsync(c => c.MaKh == id);
            // DTO
            var result = new ClientVM
            {
                MaKH = Client.MaKh,
                HoTen = Client.HoTen,
                GioiTinh = Client.GioiTinh,
                NgaySinh = Client.NgaySinh,
                DienThoai = Client.DienThoai,
                DiaChi = Client.DiaChi,
                Email = Client.Email,
                Hinh = Client.Hinh,
            };
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("MaKH, HoTen, GioiTinh, NgaySinh, DiaChi, DienThoai, Email")] ClientVM Client,
            IFormFile? Hinh)
        {
            if (ModelState.IsValid)
            {
                // Xử lý lưu ảnh
                if (Hinh != null && Hinh.Length > 0)
                {
                    Client.Hinh = MyUtil.UpLoadHinh(Hinh, "KhachHang");
                }

                var ExistsClient = await db.KhachHangs.FirstOrDefaultAsync(c => c.MaKh == Client.MaKH);
                if (ExistsClient != null)
                {
                    ExistsClient.HoTen = Client.HoTen;
                    ExistsClient.GioiTinh = Client.GioiTinh;
                    ExistsClient.NgaySinh = Client.NgaySinh;
                    ExistsClient.DienThoai = Client.DienThoai;
                    ExistsClient.DiaChi = Client.DiaChi;
                    ExistsClient.Email = Client.Email;
                    if (Client.Hinh != null)
                    {
                        ExistsClient.Hinh = Client.Hinh;
                    }
                    db.KhachHangs.Update(ExistsClient);
                    await db.SaveChangesAsync();
                    TempData[ToastMessage] = "Cập nhật thông tin người dùng thành công";
                    TempData[ToastType] = ToastTypeSuccess;
                    return Redirect("/admin/clients");
                }
                TempData[ToastMessage] = "Không tìm thấy người dùng";
                TempData[ToastType] = ToastTypeError;
                return NotFound();
            }
            TempData[ToastMessage] = "Cập nhật thông tin dùng thất bại";
            TempData[ToastType] = ToastTypeError;
            return Redirect("/admin/clients/update/" + Client.MaKH);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var Client = await db.KhachHangs.SingleOrDefaultAsync(k => k.MaKh == id);
            if (Client != null)
            {
                var HoaDons = await db.HoaDons.Where(h => h.MaKh == id).ToListAsync();
                foreach (var h in HoaDons)
                {
                    var Cthhs = await db.ChiTietHds.Where(h => h.MaHd == h.MaHd).ToListAsync();
                    db.ChiTietHds.RemoveRange(Cthhs);
                    db.Remove(h);
                    await db.SaveChangesAsync();
                }
                db.KhachHangs.Remove(Client);
                await db.SaveChangesAsync();
                TempData[ToastMessage] = "Xóa người dùng thành công";
                TempData[ToastType] = ToastTypeSuccess;
                return Redirect("/admin/clients");
            }
            TempData[ToastMessage] = "Không tồn tại người dùng";
            TempData[ToastType] = ToastTypeError;
            return NotFound();

        }
    }
}

HShop/HShop/Controllers/OrdersController.cs
using HShop.Data;
using HShop.Helpers;
using HShop.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Runtime.InteropServices;

namespace HShop.Controllers
{
    [Authorize(Roles="1")]
    public class OrdersController : Controller
    {
        private readonly Hshop2023Context db;

        public OrdersController(Hshop2023Context db)
        {
            this.db = db;
        }

        [Route("Admin/Orders/Detail/{id}")]
        public async Task<IActionResult> Detail(int id)
        {
            var hoaDons = await db.ChiTietHds
                           .Include(h => h.MaHhNavigation)
                           .Where(h => h.MaHd == id).ToListAsync();

            if (hoaDons == null)
            {
                return NotFound();
            }

            var result = hoaDons.Select(h => new DetailInvoiceVM
            {
                MaCt = h.MaCt,
                MaHd = h.MaHd,
                MaHh = h.MaHh,
                DonGia = h.DonGia,
                SoLuong = h.SoLuong,
                GiamGia = h.GiamGia,
                TenHangHoa = h.MaHhNavigation?.TenHh,
                Hinh = h.MaHhNavigation?.Hinh,
                ThanhTien = h.DonGia * h.SoLuong
            }).ToList();

            return View(result);
        }

        [Route("Admin/Orders/Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var donHang = await db.HoaDons.FirstOrDefaultAsync(h => h.MaHd == id);
            var cthds = await db.ChiTietHds.Where(c => c.MaHd == id).ToListAsync();
            db.HoaDons.Remove(donHang);
            db.ChiTietHds.RemoveRange(cthds);
            await db.SaveChangesAsync();
            return Redirect("/Admin/Orders");
        }

        public async Task<IActionResult> Confirm(int id, DateTime deliveryDate)
        {
			if (deliveryDate < DateTime.Now.Date)
			{
				TempData["ErrorMessage"] = "Ngày giao hàng không thể ở trong quá khứ";
                return Redirect("/admin/orders/detail/" + id);
			}
			using (var transaction = await db.Database.BeginTransactionAsync())
            {
                try
                {
					var donHang = await db.HoaDons.SingleOrDefaultAsync(h => h.MaHd == id);
					if (donHang == null)
					{
						return NotFound();
					}
					donHang.NgayGiao = deliveryDate;
					donHang.MaTrangThai = 2;
					var MaKH = HttpContext.User.Identity.IsAuthenticated ? HttpContext.User.FindFirst(MyConstant.CLAIM_CUSTOMERID)?.Value : "Guest";
					if (MaKH == "Guest")
					{
						return Redirect("/404");
					}
					donHang.MaNv = MaKH;
                    await db.SaveChangesAsync();
					await transaction.CommitAsync();
					TempData["SuccessMessage"] = "Đã xác nhận đơn hàng thành công";
					return Redirect("/admin/orders");
				}
				catch (Exception ex)
				{
					await transaction.RollbackAsync();
					// Log lỗi ở đây (sử dụng ILogger)
					TempData["ErrorMessage"] = "Có lỗi xảy ra khi xác nhận đơn hàng";
					return Redirect("/admin/orders/detail/" + id);
				}
			}
				
        }
    }
}

HShop/HShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HShop.Data;
using HShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using HShop.Helpers;

namespace HShop.Controllers
{
	[Authorize(Roles = "1")]
	public class ProductsController : Controller
	{
		private readonly Hshop2023Context db;

		public ProductsController(Hshop2023Context db)
		{
			this.db = db;
		}

		// GET: HangHoas/Details/5
		[Route("/admin/products/detail/{id}")]
		public async Task<IActionResult> Detail(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var product = await db.HangHoas
				.Include(h => h.MaLoaiNavigation)
				.Include(h => h.MaNccNavigation)
				.FirstOrDefaultAsync(m => m.MaHh == id);

			if (product == null)
			{
				return NotFound();
			}

			var ProductDTO = new ProductAdminVM
			{
				MaHh = product.MaHh,
				TenHh = product.TenHh,
				TenAlias = product.TenAlias,
				MaLoai = product.MaLoai,
				MoTaDonVi = product.MoTaDonVi,
				DonGia = product.DonGia,
				Hinh = product.Hinh,
				NgaySx = product.NgaySx,
				GiamGia = product.GiamGia,
				SoLanXem = product.SoLanXem,
				MoTa = product.MoTa,
				MaNcc = product.MaNcc,
				MaLoaiNavigation = product.MaLoaiNavigation,
				MaNccNavigation = product.MaNccNavigation
			};

			return View(ProductDTO);
		}

		// GET: HangHoas/Create

		[HttpGet]
		[Route("/admin/products/create")]
		public IActionResult Create()
		{
			ViewData["MaLoai"] = new SelectList(db.Loais, "MaLoai", "MaLoai");
			ViewData["MaNcc"] = new SelectList(db.NhaCungCaps, "MaNcc", "MaNcc");
			return View();
		}

		// POST: HangHoas/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateProduct([Bind("MaHh,TenHh,TenAlias,MaLoai,MoTaDonVi,DonGia,NgaySx,GiamGia,SoLanXem,MoTa,MaNcc")] ProductAdminVM hangHoa,
			IFormFile Hinh)
		{
			if (ModelState.IsValid)
			{
				// Xử lý lưu ảnh
				if (Hinh != null && Hinh.Length > 0)
				{
					hangHoa.Hinh = MyUtil.UpLoadHinh(Hinh, "HangHoa");
				}
				var product = new HangHoa
				{
					MaHh = hangHoa.MaHh,
					TenHh = hangHoa.TenHh,
					TenAlias = hangHoa.TenAlias,
					MaLoai = hangHoa.MaLoai,
					Hinh = hangHoa.Hinh,
					MoTaDonVi = hangHoa.MoTaDonVi,
					DonGia = hangHoa.DonGia,
					NgaySx = hangHoa.NgaySx,
					GiamGia = hangHoa.GiamGia,
					SoLanXem = hangHoa.SoLanXem,
					MoTa = hangHoa.MoTa,
					MaNcc = hangHoa.MaNcc,
				};

				await db.HangHoas.AddAsync(product);
				await db.SaveChangesAsync();
				return Redirect("/admin/products");
			}

			// Nếu có lỗi, trả về View với dữ liệu cũ
			ViewData["MaLoai"] = new SelectList(db.Loais, "MaLoai", "TenLoai", hangHoa.MaLoai);
			ViewData["MaNcc"] = new SelectList(db.NhaCungCaps, "MaNcc", "TenNcc", hangHoa.MaNcc);
			return Redirect("/admin/products/create");
		}

		// GET: HangHoas/Edit/5
		[Route("admin/products/update/{id}")]
		public async Task<IActionResult> Update(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var product = await db.HangHoas.FindAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			var ProductDTO = new ProductAdminVM
			{
				MaHh = product.MaHh,
				TenHh = product.TenHh,
				TenAlias = product.TenAlias,
				MaLoai = product.MaLoai,
				MoTaDonVi = product.MoTaDonVi,
				DonGia = product.DonGia,
				Hinh = product.Hinh,
				NgaySx = product.NgaySx,
				GiamGia = product.GiamGia,
				SoLanXem = product.SoLanXem,
				MoTa = product.MoTa,
				MaNcc = product.MaNcc,
				MaLoaiNavigation = product.MaLoaiNavigation,
				MaNccNavigation = product.MaNccNavigation
			};
			ViewData["MaLoai"] = new SelectList(db.Loais, "MaLoai", "MaLoai", product.MaLoai);
			ViewData["MaNcc"] = new SelectList(db.NhaCungCaps, "MaNcc", "MaNcc", product.MaNcc);
			return View(ProductDTO);
		}

		// POST: HangHoas/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("MaHh,TenHh,TenAlias,MaLoai,MoTaDonVi,DonGia,Hinh,NgaySx,GiamGia,SoLanXem,MoTa,MaNcc")] ProductAdminVM product)
		{
			if (id != product.MaHh)
			{
				return NotFound();
			}
			try
			{
				var existingProduct = await db.HangHoas.FirstOrDefaultAsync(h => h.MaHh == id);
				// Gán các giá trị từ ViewModel sang Entity
				existingProduct.TenHh = product.TenHh;
				existingProduct.TenAlias = product.TenAlias;
				existingProduct.MaLoai = product.MaLoai;
				existingProduct.MoTaDonVi = product.MoTaDonVi;
				existingProduct.DonGia = product.DonGia;
				if (product.Hinh != null)
				{
					existingProduct.Hinh = product.Hinh;
				}
				existingProduct.NgaySx = product.NgaySx;
				existingProduct.GiamGia = product.GiamGia;
				existingProduct.SoLanXem = product.SoLanXem;
				existingProduct.MoTa = product.MoTa;
				existingProduct.MaNcc = product.MaNcc;

				// Cập nhật và lưu thay đổi
				db.HangHoas.Update(existingProduct);
				await db.SaveChangesAsync();

				return Redirect("/admin/products");
			}
			catch (DbUpdateConcurrencyException)
			{
				if (!HangHoaExists(product.MaHh))
				{
					return NotFound();
				}
				else
				{
					TempData["Message"] = "Model state is invalid";
					return Redirect("/admin");
				}
			}
		}

		public async Task<IActionResult> Delete(int id)
		{
			var cthhs = await db.ChiTietHds.FirstOrDefaultAsync(c => c.MaHh == id);
			if(cthhs == null)
			{
				var hangHoa = await db.HangHoas.FindAsync(id);
				if (hangHoa != null)
				{
					db.HangHoas.Remove(hangHoa);
				}

				await db.SaveChangesAsync();
				return Redirect("/admin/products");
			}
			TempData["ErrorMessage"] = "Không thể xóa hàng hóa vì đang được sử dụng trong hóa đơn!";
			return Redirect("/admin/products");
		}

		private bool HangHoaExists(int id)
		{
			return db.HangHoas.Any(e => e.MaHh == id);
		}
	}
}

HShop/HShop/Views/Admin/Categories.cshtml
@model IEnumerable<HShop.ViewModels.CategoryVM>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Quản lý loại hàng hóa";
}
<div class="card">
    <div class="card-header">
        <h4 class="mb-0 text-center" style="font-size: 20px">Danh sách loại hàng hóa</h4>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="hoaDonTable">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center">Mã loại</th>
                        <th class="text-center">Ảnh minh họa</th>
                        <th class="text-center">Tên loại</th>
                        <th class="text-center">Tên alias</th>
                        <th class="text-center">Mô tả</th>
                        <th class="text-center">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-center">@item.MaLoai</td>
                            <td class="text-center"><img src="~/Hinh/Loai/@item.Hinh" alt="@item.TenLoai" width="120" height="110"></td>
                            <td class="text-center">@item.TenLoai</td>
                            <td class="text-center">@item.TenLoaiAlias</td>
                            <td class="text-center">@item.MoTa</td>
                            <td class="text-center">
                                <div class="btn-group d-flex justify-center gap-2" role="group">
                                    <a asp-action="Delete" asp-controller="Categories" asp-route-id="@item.MaLoai"
                                       class="btn btn-sm btn-delete" title="Xóa loai">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.btn-delete').click(function (e) {
                e.preventDefault(); // Ngăn chặn hành vi mặc định
                var deleteUrl = $(this).attr('href'); // Lấy URL từ thẻ a

                // Hiển thị hộp thoại confirm
                if (confirm('Bạn có chắc chắn muốn xóa loại hàng hóa này?')) {
                    window.location.href = deleteUrl; // Chuyển hướng nếu đồng ý
                }
            });
        });
    </script>
}

HShop/HShop/Views/Admin/Clients.cshtml
@using HShop.Helpers
@model IEnumerable<HShop.ViewModels.ClientVM>
@{
	Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
	ViewBag.Title = "Quản lý người dùng";
}
<div class="card">
	<div class="flex-between mb-2 flex-sm-column">
		<div>
			<a asp-action="Create" asp-controller="Clients" class="btn btn-success featured">
				<i class="fa fa-plus"></i> Thêm người dùng
			</a>
		</div>
		<form asp-action="Clients" asp-controller="Admin" method="post" class="d-flex flex-md-row flex-grow-1 gap-2">
			<div class="flex-grow-1">
				<select class="form-select featured" name="VaiTro">
					<option value="">Loại người dùng</option>
					@foreach (var role in ViewBag.Roles) // Giả sử bạn đã truyền Categories từ controller
					{
						<option value="@role">@MyUtil.convertRole(@role)</option>
					}
				</select>
			</div>
			<div class="flex-grow-1">
				<div class="input-group">
					<input type="number" class="form-control featured" min="5" name="pageSize" placeholder="Kích thước trang">
				</div>
			</div>
			<div class="d-flex gap-2">
				<button type="submit" class="btn btn-filter featured">Filter</button>
				<button type="button" class="btn btn-reset featured" onclick="resetFilters()">
					<i class="fa fa-refresh"></i> Reset
				</button>
			</div>
		</form>
	</div>
	<div class="card-header">
		<h4 class="mb-0 text-center" style="font-size: 20px">Danh sách người dùng</h4>
	</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-striped table-hover" id="hoaDonTable">
				<thead class="thead-dark">
					<tr>
						<th class="text-center">STT</th>
						<th class="text-center">Ảnh minh họa</th>
						<th class="text-center">Tên người dùng</th>
						<th class="text-center">Giới tính</th>
						<th class="text-center">Điện thoại</th>
						<th class="text-center">Địa chỉ</th>
						<th class="text-center">Email</th>
						<th class="text-center">Thao tác</th>
					</tr>
				</thead>
				<tbody>
					@{
						int j = 1; 
					}
					@foreach (var item in Model)
					{
						<tr>
							<td class="text-center">@(j++)</td>
							<td class="text-center">
								@if (!String.IsNullOrEmpty(item.Hinh))
								{
									<img src="~/Hinh/KhachHang/@item.Hinh"
										 alt="@item.HoTen"
										 style="width: 150px; height: 150px; object-fit: cover;"
										 class="img-thumbnail">
								}
								else
								{
									<div class="mt-2">
										<div style="width: 150px; height: 150px;
                        border: 1px solid #ddd;
                        display: flex;
                        align-items: center;
                        justify-content: center;
                        background-color: #f8f9fa;"
											 class="img-thumbnail">
											<span style="color: #666; font-size: 14px;">No Image</span>
										</div>
									</div>
								}
							</td>
							<td class="text-center">@item.HoTen</td>
							<td class="text-center">@(item.GioiTinh? "Nam" : "Nữ")</td>
							<td class="text-center">@item.DienThoai</td>
							<td class="text-center">@item.DiaChi</td>
							<td class="text-center">@item.Email</td>
							<td class="text-center">
								<div class="btn-group flex-center gap-2" role="group">
									<a asp-action="Update" asp-controller="Clients" asp-route-id="@item.MaKH"
									   class="btn btn-sm btn-warning" title="Chỉnh sửa thông tin">
										<i class="fa fa-edit"></i>
									</a>
									<a asp-action="Delete" asp-controller="Clients" asp-route-id="@item.MaKH"
									   class="btn btn-sm btn-delete" title="Xóa người dùng">
										<i class="fa fa-trash"></i>
									</a>
								</div>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- Phần phân trang -->
<div class="flex-center">
	<div class="col-md-10">
		<nav aria-label="Page navigation">
			<ul class="pagination flex-center">
				@if (ViewBag.CurrentPage > 1)
				{
					<li class="page-item">
						<a class="page-link" href="@Url.Action("Clients", new { pageNumber = ViewBag.CurrentPage - 1, pageSize = ViewBag.PageSize, maLoai = ViewBag.CurrentMaLoai })">&laquo;</a>
					</li>
				}

				@for (int i = 1; i <= ViewBag.TotalPages; i++)
				{
					<li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
						<a class="page-link" href="@Url.Action("Clients", new { pageNumber = i, pageSize = ViewBag.PageSize, maLoai = ViewBag.CurrentMaLoai })">@i</a>
					</li>
				}

				@if (ViewBag.CurrentPage < ViewBag.TotalPages)
				{
					<li class="page-item">
						<a class="page-link" href="@Url.Action("Clients", new { pageNumber = ViewBag.CurrentPage + 1, pageSize = ViewBag.PageSize, maLoai = ViewBag.CurrentMaLoai })">&raquo;</a>
					</li>
				}
			</ul>
		</nav>
	</div>
</div>

@section Scripts {
	<script>
		$(document).ready(function () {
			$('.btn-delete').click(function (e) {
				e.preventDefault(); // Ngăn chặn hành vi mặc định
				var deleteUrl = $(this).attr('href'); // Lấy URL từ thẻ a

				// Hiển thị hộp thoại confirm
				if (confirm('Bạn có chắc chắn muốn xóa người dùng này?')) {
					window.location.href = deleteUrl; // Chuyển hướng nếu đồng ý
				}
			});
		});
		function resetFilters() {
			document.getElementById("categoryFilter").value = "";
			document.querySelector("input[name='pageSize']").value = 5;

			window.location.href = `@Url.Action("Index")?pageNumber=1&pageSize=5`
		}
	</script>
}

HShop/HShop/Views/Admin/Orders.cshtml
@using HShop.Helpers
@model IEnumerable<HShop.ViewModels.InvoiceVM>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Quản lý đơn hàng";
}
<div class="card">
    <div class="card-header">
        <h4 class="mb-0 text-center" style="font-size: 20px">Danh sách đơn hàng</h4>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="hoaDonTable">
                <thead class="thead-dark">
                    <tr>
                        <th>Mã HD</th>
                        <th>Ngày tạo</th>
                        <th>Khách hàng</th>
                        <th>Địa chỉ</th>
                        <th>PT Thanh toán</th>
                        <th>PT Vận chuyển</th>
                        <th>Trạng thái</th>
                        <th>Điện thoại</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaHd</td>
                            <td>@item.NgayDat.ToString("dd/MM/yyyy HH:mm")</td>
                            <td>@item.HoTen</td>
                            <td>@item.DiaChi</td>
                            <td>@item.CachThanhToan</td>
                            <td>@item.CachVanChuyen</td>
                            <td>
                                <span class="badge-@item.TrangThai">
                                    @MyUtil.convertStatus(item.TrangThai)
                                </span>
                            </td>
                            <td>@item.DienThoai</td>
                            <td>
                                <div class="btn-group d-flex justify-center gap-2" role="group">
                                    <a asp-action="Detail" asp-controller="Orders" asp-route-id="@item.MaHd"
                                       class="btn btn-sm btn-info" title="Xem chi tiết">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a asp-action="Delete" asp-controller="Orders" asp-route-id="@item.MaHd"
                                       class="btn btn-sm btn-delete" title="Xóa đơn hàng">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.btn-delete').click(function (e) {
                e.preventDefault(); // Ngăn chặn hành vi mặc định
                var deleteUrl = $(this).attr('href'); // Lấy URL từ thẻ a

                // Hiển thị hộp thoại confirm
                if (confirm('Bạn có chắc chắn muốn xóa đơn hàng này?')) {
                    window.location.href = deleteUrl; // Chuyển hướng nếu đồng ý
                }
            });
        });
    </script>
}